# cmake/embed_shaders.ps1
# Compiles all *.comp shaders under -ShaderDir to SPIR-V using -Validator and
# emits a C++ header (-OutFile) embedding each module as a uint32_t array plus
# a GetBurstSpirv(name) accessor. Invoked from CMake at configure time.
param(
    [Parameter(Mandatory=$true)][string]$Validator,
    [Parameter(Mandatory=$true)][string]$ShaderDir,
    [Parameter(Mandatory=$true)][string]$OutFile,
    [string]$WorkDir
)

$ErrorActionPreference = "Stop"
if (-not $WorkDir) { $WorkDir = $ShaderDir }
$incArg = "-I" + $ShaderDir
$tempBase = Join-Path $env:TEMP "burstmerge_spv"
if (-not (Test-Path $tempBase)) { New-Item -ItemType Directory -Path $tempBase -Force | Out-Null }

$shaders = Get-ChildItem -LiteralPath $ShaderDir -Filter "*.comp" | Sort-Object Name
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// Auto-generated by cmake/embed_shaders.ps1 - DO NOT EDIT.")
[void]$sb.AppendLine("// Embedded SPIR-V for all BurstMerge compute shaders.")
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("#include <cstdint>")
[void]$sb.AppendLine("#include <cstring>")
[void]$sb.AppendLine("namespace burstmerge { namespace vulkan {")
[void]$sb.AppendLine("")

$names = New-Object System.Collections.Generic.List[string]
foreach ($s in $shaders) {
    $base = $s.BaseName
    $names.Add($base)
    $spv = Join-Path $tempBase ($base + ".spv")
    $args = @("-V", $incArg, $s.FullName, "-o", $spv)
    & $Validator @args 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) {
        throw "glslangValidator failed for $($s.Name) (exit $LASTEXITCODE)"
    }
    $bytes = [System.IO.File]::ReadAllBytes($spv)
    if ($bytes.Length -eq 0) { throw "Empty SPIR-V for $($s.Name)" }
    $numWords = [int]($bytes.Length / 4)
    [void]$sb.AppendLine("static const uint32_t kSpv_$base[] = {")
    $line = New-Object System.Text.StringBuilder
    for ($i = 0; $i -lt $numWords; ++$i) {
        $w = [uint32]$bytes[$i*4] -bor ([uint32]$bytes[$i*4+1] -shl 8) -bor ([uint32]$bytes[$i*4+2] -shl 16) -bor ([uint32]$bytes[$i*4+3] -shl 24)
        [void]$line.Append(("0x{0:x8}," -f $w))
        if ((($i + 1) % 12) -eq 0) { [void]$sb.AppendLine($line.ToString()); $line.Clear() | Out-Null }
    }
    $tail = $line.ToString()
    if ($tail.Length -gt 0) { [void]$sb.AppendLine($tail) }
    [void]$sb.AppendLine("};")
    [void]$sb.AppendLine("static const uint32_t kSpv_${base}_words = $numWords;")
    [void]$sb.AppendLine("")
}

# Accessor: name -> {data,words}
[void]$sb.AppendLine("struct SpirvModule { const uint32_t* data; uint32_t words; };")
[void]$sb.AppendLine("inline bool GetBurstSpirvByName(const char* name, SpirvModule& out) {")
foreach ($n in $names) {
    [void]$sb.AppendLine("    if (std::strcmp(name, `"$n`") == 0) { out.data = kSpv_$n; out.words = kSpv_${n}_words; return true; }")
}
[void]$sb.AppendLine("    return false;")
[void]$sb.AppendLine("}")

[void]$sb.AppendLine("")
[void]$sb.AppendLine("} } // namespace vulkan::burstmerge")

$outDir = Split-Path $OutFile -Parent
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }
[System.IO.File]::WriteAllText($OutFile, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Output ("Embedded " + $names.Count + " shaders into " + $OutFile)
